remove xmlrpclib from requires since koji fails with: TypeError: dumps() got an unexpected keyword argument 'allow_none'
Signed-off-by: Gowrishankar Rajaiyan <gsr@redhat.com>